/* Generated by Yosys 0.60+8 (git sha1 0e31e389f, g++ 13.1.0-8ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../rtl/4bitalu.v:1.1-78.10" *)
module alu_4bit(A, B, ALU_CTRL, RESULT, CARRY_OUT, ZERO, OVERFLOW);
  (* src = "../rtl/4bitalu.v:4.24-4.25" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "../rtl/4bitalu.v:5.24-5.25" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "../rtl/4bitalu.v:6.24-6.32" *)
  input [2:0] ALU_CTRL;
  wire [2:0] ALU_CTRL;
  (* src = "../rtl/4bitalu.v:8.24-8.30" *)
  output [3:0] RESULT;
  wire [3:0] RESULT;
  (* src = "../rtl/4bitalu.v:9.24-9.33" *)
  output CARRY_OUT;
  wire CARRY_OUT;
  (* src = "../rtl/4bitalu.v:10.24-10.28" *)
  output ZERO;
  wire ZERO;
  (* src = "../rtl/4bitalu.v:11.24-11.32" *)
  output OVERFLOW;
  wire OVERFLOW;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  (* src = "../rtl/4bitalu.v:6.24-6.32" *)
  wire _101_;
  (* src = "../rtl/4bitalu.v:6.24-6.32" *)
  wire _102_;
  (* src = "../rtl/4bitalu.v:6.24-6.32" *)
  wire _103_;
  (* src = "../rtl/4bitalu.v:4.24-4.25" *)
  wire _104_;
  (* src = "../rtl/4bitalu.v:4.24-4.25" *)
  wire _105_;
  (* src = "../rtl/4bitalu.v:4.24-4.25" *)
  wire _106_;
  (* src = "../rtl/4bitalu.v:4.24-4.25" *)
  wire _107_;
  (* src = "../rtl/4bitalu.v:5.24-5.25" *)
  wire _108_;
  (* src = "../rtl/4bitalu.v:5.24-5.25" *)
  wire _109_;
  (* src = "../rtl/4bitalu.v:5.24-5.25" *)
  wire _110_;
  (* src = "../rtl/4bitalu.v:5.24-5.25" *)
  wire _111_;
  (* src = "../rtl/4bitalu.v:9.24-9.33" *)
  wire _112_;
  (* src = "../rtl/4bitalu.v:11.24-11.32" *)
  wire _113_;
  (* src = "../rtl/4bitalu.v:8.24-8.30" *)
  wire _114_;
  (* src = "../rtl/4bitalu.v:8.24-8.30" *)
  wire _115_;
  (* src = "../rtl/4bitalu.v:8.24-8.30" *)
  wire _116_;
  (* src = "../rtl/4bitalu.v:8.24-8.30" *)
  wire _117_;
  (* src = "../rtl/4bitalu.v:10.24-10.28" *)
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  sky130_fd_sc_hd__nand2b_1 _174_ (
    .A_N(_103_),
    .B(_102_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(_108_),
    .B(_104_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor2_1 _176_ (
    .A(_101_),
    .B(_119_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand3_1 _177_ (
    .A(_108_),
    .B(_104_),
    .C(_119_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__o21ai_0 _178_ (
    .A1(_108_),
    .A2(_104_),
    .B1(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a21oi_1 _179_ (
    .A1(_120_),
    .A2(_121_),
    .B1(_123_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _180_ (
    .A(_109_),
    .B(_105_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__xor2_1 _181_ (
    .A(_109_),
    .B(_105_),
    .X(_125_)
  );
  sky130_fd_sc_hd__nor3b_1 _182_ (
    .A(_102_),
    .B(_101_),
    .C_N(_103_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__clkinv_1 _183_ (
    .A(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2b_1 _184_ (
    .A_N(_103_),
    .B(_101_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__and3_1 _185_ (
    .A(_119_),
    .B(_127_),
    .C(_128_),
    .X(_129_)
  );
  sky130_fd_sc_hd__xor2_1 _186_ (
    .A(_108_),
    .B(_109_),
    .X(_130_)
  );
  sky130_fd_sc_hd__xnor2_1 _187_ (
    .A(_105_),
    .B(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _188_ (
    .A(_120_),
    .B(_125_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _189_ (
    .A(_102_),
    .SLEEP(_128_),
    .X(_133_)
  );
  sky130_fd_sc_hd__a211oi_1 _190_ (
    .A1(_120_),
    .A2(_131_),
    .B1(_132_),
    .C1(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _191_ (
    .A1(_109_),
    .A2(_105_),
    .B1(_101_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nor3_1 _192_ (
    .A(_119_),
    .B(_124_),
    .C(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__xnor2_1 _193_ (
    .A(_120_),
    .B(_125_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a221oi_1 _194_ (
    .A1(_125_),
    .A2(_126_),
    .B1(_129_),
    .B2(_137_),
    .C1(_136_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2b_1 _195_ (
    .A_N(_134_),
    .B(_138_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _196_ (
    .A1_N(_120_),
    .A2_N(_125_),
    .B1(_130_),
    .B2(_105_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__or3_1 _197_ (
    .A(_108_),
    .B(_109_),
    .C(_110_),
    .X(_140_)
  );
  sky130_fd_sc_hd__o21ai_0 _198_ (
    .A1(_108_),
    .A2(_109_),
    .B1(_110_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__and3_1 _199_ (
    .A(_106_),
    .B(_140_),
    .C(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _200_ (
    .A1(_140_),
    .A2(_141_),
    .B1(_106_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor3_1 _201_ (
    .A(_139_),
    .B(_142_),
    .C(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o21a_1 _202_ (
    .A1(_142_),
    .A2(_143_),
    .B1(_139_),
    .X(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(_110_),
    .B(_106_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a21oi_1 _204_ (
    .A1(_110_),
    .A2(_106_),
    .B1(_101_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(_110_),
    .B(_106_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__xnor2_1 _206_ (
    .A(_110_),
    .B(_106_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a22oi_1 _207_ (
    .A1(_108_),
    .A2(_104_),
    .B1(_109_),
    .B2(_105_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _208_ (
    .A1(_124_),
    .A2(_150_),
    .B1(_149_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__or3_1 _209_ (
    .A(_124_),
    .B(_149_),
    .C(_150_),
    .X(_152_)
  );
  sky130_fd_sc_hd__o32ai_1 _210_ (
    .A1(_119_),
    .A2(_147_),
    .A3(_148_),
    .B1(_149_),
    .B2(_127_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a31oi_1 _211_ (
    .A1(_129_),
    .A2(_151_),
    .A3(_152_),
    .B1(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__o31ai_1 _212_ (
    .A1(_133_),
    .A2(_144_),
    .A3(_145_),
    .B1(_154_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o21ba_1 _213_ (
    .A1(_139_),
    .A2(_143_),
    .B1_N(_142_),
    .X(_155_)
  );
  sky130_fd_sc_hd__xor2_1 _214_ (
    .A(_111_),
    .B(_140_),
    .X(_156_)
  );
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(_107_),
    .B(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__xnor2_1 _216_ (
    .A(_107_),
    .B(_156_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__xnor2_1 _217_ (
    .A(_155_),
    .B(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__and2_0 _218_ (
    .A(_111_),
    .B(_107_),
    .X(_160_)
  );
  sky130_fd_sc_hd__nor2_1 _219_ (
    .A(_111_),
    .B(_107_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nor2_1 _220_ (
    .A(_119_),
    .B(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__o21ai_0 _221_ (
    .A1(_101_),
    .A2(_160_),
    .B1(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _222_ (
    .A(_160_),
    .SLEEP(_161_),
    .X(_164_)
  );
  sky130_fd_sc_hd__o31ai_1 _223_ (
    .A1(_124_),
    .A2(_148_),
    .A3(_150_),
    .B1(_146_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o21a_1 _224_ (
    .A1(_127_),
    .A2(_164_),
    .B1(_163_),
    .X(_166_)
  );
  sky130_fd_sc_hd__xnor2_1 _225_ (
    .A(_164_),
    .B(_165_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(_129_),
    .B(_167_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__o211ai_1 _227_ (
    .A1(_133_),
    .A2(_159_),
    .B1(_166_),
    .C1(_168_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nor4_1 _228_ (
    .A(_114_),
    .B(_115_),
    .C(_116_),
    .D(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _229_ (
    .A1(_146_),
    .A2(_152_),
    .B1(_161_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o21ai_0 _230_ (
    .A1(_160_),
    .A2(_165_),
    .B1(_129_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__xor2_1 _231_ (
    .A(_155_),
    .B(_156_),
    .X(_171_)
  );
  sky130_fd_sc_hd__o32ai_1 _232_ (
    .A1(_133_),
    .A2(_164_),
    .A3(_171_),
    .B1(_170_),
    .B2(_169_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nor2_1 _233_ (
    .A(_155_),
    .B(_157_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _234_ (
    .A1(_107_),
    .A2(_156_),
    .B1(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__o22ai_1 _235_ (
    .A1(_161_),
    .A2(_170_),
    .B1(_173_),
    .B2(_133_),
    .Y(_112_)
  );
  assign _108_ = B[0];
  assign _104_ = A[0];
  assign _102_ = ALU_CTRL[1];
  assign _101_ = ALU_CTRL[0];
  assign _103_ = ALU_CTRL[2];
  assign RESULT[0] = _114_;
  assign _109_ = B[1];
  assign _105_ = A[1];
  assign RESULT[1] = _115_;
  assign _110_ = B[2];
  assign _106_ = A[2];
  assign RESULT[2] = _116_;
  assign _111_ = B[3];
  assign _107_ = A[3];
  assign RESULT[3] = _117_;
  assign ZERO = _118_;
  assign OVERFLOW = _113_;
  assign CARRY_OUT = _112_;
endmodule
