/* Generated by Yosys 0.60+8 (git sha1 0e31e389f, g++ 13.1.0-8ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../rtl/4bitalu.v:10.1-105.10" *)
module alu_4bit(A, B, ALU_CTRL, RESULT, CARRY_OUT, OVERFLOW, ZERO, scan_enable, scan_in, scan_out);
  (* src = "../rtl/4bitalu.v:12.23-12.24" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "../rtl/4bitalu.v:13.23-13.24" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "../rtl/4bitalu.v:14.23-14.31" *)
  input [2:0] ALU_CTRL;
  wire [2:0] ALU_CTRL;
  (* src = "../rtl/4bitalu.v:17.23-17.29" *)
  output [3:0] RESULT;
  wire [3:0] RESULT;
  (* src = "../rtl/4bitalu.v:18.23-18.32" *)
  output CARRY_OUT;
  wire CARRY_OUT;
  (* src = "../rtl/4bitalu.v:19.23-19.31" *)
  output OVERFLOW;
  wire OVERFLOW;
  (* src = "../rtl/4bitalu.v:20.23-20.27" *)
  output ZERO;
  wire ZERO;
  (* src = "../rtl/4bitalu.v:22.17-22.28" *)
  input scan_enable;
  wire scan_enable;
  (* src = "../rtl/4bitalu.v:23.17-23.24" *)
  input scan_in;
  wire scan_in;
  (* src = "../rtl/4bitalu.v:24.17-24.25" *)
  output scan_out;
  wire scan_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  (* src = "../rtl/4bitalu.v:14.23-14.31" *)
  wire _132_;
  (* src = "../rtl/4bitalu.v:14.23-14.31" *)
  wire _133_;
  (* src = "../rtl/4bitalu.v:14.23-14.31" *)
  wire _134_;
  (* src = "../rtl/4bitalu.v:12.23-12.24" *)
  wire _135_;
  (* src = "../rtl/4bitalu.v:12.23-12.24" *)
  wire _136_;
  (* src = "../rtl/4bitalu.v:12.23-12.24" *)
  wire _137_;
  (* src = "../rtl/4bitalu.v:12.23-12.24" *)
  wire _138_;
  (* src = "../rtl/4bitalu.v:13.23-13.24" *)
  wire _139_;
  (* src = "../rtl/4bitalu.v:13.23-13.24" *)
  wire _140_;
  (* src = "../rtl/4bitalu.v:13.23-13.24" *)
  wire _141_;
  (* src = "../rtl/4bitalu.v:13.23-13.24" *)
  wire _142_;
  (* src = "../rtl/4bitalu.v:18.23-18.32" *)
  wire _143_;
  (* src = "../rtl/4bitalu.v:19.23-19.31" *)
  wire _144_;
  (* src = "../rtl/4bitalu.v:17.23-17.29" *)
  wire _145_;
  (* src = "../rtl/4bitalu.v:17.23-17.29" *)
  wire _146_;
  (* src = "../rtl/4bitalu.v:17.23-17.29" *)
  wire _147_;
  (* src = "../rtl/4bitalu.v:17.23-17.29" *)
  wire _148_;
  (* src = "../rtl/4bitalu.v:20.23-20.27" *)
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  sky130_fd_sc_hd__nand3b_1 _222_ (
    .A_N(_133_),
    .B(_132_),
    .C(_134_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _223_ (
    .A(_135_),
    .B(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_132_),
    .B(_133_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _225_ (
    .A(_134_),
    .B(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__and2_0 _226_ (
    .A(_139_),
    .B(_135_),
    .X(_154_)
  );
  sky130_fd_sc_hd__nor3b_1 _227_ (
    .A(_134_),
    .B(_133_),
    .C_N(_132_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__clkinv_1 _228_ (
    .A(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a211oi_1 _229_ (
    .A1(_134_),
    .A2(_132_),
    .B1(_133_),
    .C1(_154_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _230_ (
    .A(_133_),
    .SLEEP(_132_),
    .X(_158_)
  );
  sky130_fd_sc_hd__and3_1 _231_ (
    .A(_134_),
    .B(_132_),
    .C(_133_),
    .X(_159_)
  );
  sky130_fd_sc_hd__o211ai_1 _232_ (
    .A1(_139_),
    .A2(_134_),
    .B1(_158_),
    .C1(_135_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__o22ai_1 _233_ (
    .A1(_139_),
    .A2(_135_),
    .B1(_153_),
    .B2(_157_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a21oi_1 _234_ (
    .A1(_139_),
    .A2(_159_),
    .B1(_151_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand3_1 _235_ (
    .A(_160_),
    .B(_161_),
    .C(_162_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(_139_),
    .B(_140_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _237_ (
    .A(_139_),
    .SLEEP(_140_),
    .X(_164_)
  );
  sky130_fd_sc_hd__and3_1 _238_ (
    .A(_136_),
    .B(_163_),
    .C(_164_),
    .X(_165_)
  );
  sky130_fd_sc_hd__a21oi_1 _239_ (
    .A1(_163_),
    .A2(_164_),
    .B1(_136_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o21bai_1 _240_ (
    .A1(_165_),
    .A2(_166_),
    .B1_N(_154_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(_140_),
    .B(_136_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(_140_),
    .B(_136_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__xnor2_1 _243_ (
    .A(_140_),
    .B(_136_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__a21oi_1 _244_ (
    .A1(_154_),
    .A2(_170_),
    .B1(_156_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(_167_),
    .B(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor3_1 _246_ (
    .A(_134_),
    .B(_132_),
    .C(_133_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__xnor2_1 _247_ (
    .A(_154_),
    .B(_170_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor3_1 _248_ (
    .A(_134_),
    .B(_152_),
    .C(_168_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor2_1 _249_ (
    .A(_136_),
    .B(_150_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__or3b_1 _250_ (
    .A(_132_),
    .B(_133_),
    .C_N(_134_),
    .X(_177_)
  );
  sky130_fd_sc_hd__nand2b_1 _251_ (
    .A_N(_134_),
    .B(_158_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__o22ai_1 _252_ (
    .A1(_170_),
    .A2(_177_),
    .B1(_178_),
    .B2(_169_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a2111oi_0 _253_ (
    .A1(_140_),
    .A2(_159_),
    .B1(_175_),
    .C1(_176_),
    .D1(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__a32oi_1 _254_ (
    .A1(_134_),
    .A2(_136_),
    .A3(_158_),
    .B1(_173_),
    .B2(_174_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand3_1 _255_ (
    .A(_172_),
    .B(_180_),
    .C(_181_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a32oi_1 _256_ (
    .A1(_136_),
    .A2(_163_),
    .A3(_164_),
    .B1(_170_),
    .B2(_154_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__or3_1 _257_ (
    .A(_139_),
    .B(_140_),
    .C(_141_),
    .X(_183_)
  );
  sky130_fd_sc_hd__o21ai_0 _258_ (
    .A1(_139_),
    .A2(_140_),
    .B1(_141_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__and3_1 _259_ (
    .A(_137_),
    .B(_183_),
    .C(_184_),
    .X(_185_)
  );
  sky130_fd_sc_hd__a21oi_1 _260_ (
    .A1(_183_),
    .A2(_184_),
    .B1(_137_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__o21ai_0 _261_ (
    .A1(_185_),
    .A2(_186_),
    .B1(_182_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__o31a_1 _262_ (
    .A1(_182_),
    .A2(_185_),
    .A3(_186_),
    .B1(_155_),
    .X(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(_187_),
    .B(_188_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nand2_1 _264_ (
    .A(_141_),
    .B(_137_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(_141_),
    .B(_137_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a22oi_1 _266_ (
    .A1(_139_),
    .A2(_135_),
    .B1(_140_),
    .B2(_136_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__o21ai_0 _267_ (
    .A1(_168_),
    .A2(_192_),
    .B1(_191_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__o311ai_0 _268_ (
    .A1(_168_),
    .A2(_191_),
    .A3(_192_),
    .B1(_193_),
    .C1(_173_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nand3b_1 _269_ (
    .A_N(_134_),
    .B(_137_),
    .C(_158_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__a21oi_1 _270_ (
    .A1(_137_),
    .A2(_153_),
    .B1(_141_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__a21o_1 _271_ (
    .A1(_152_),
    .A2(_195_),
    .B1(_196_),
    .X(_197_)
  );
  sky130_fd_sc_hd__o22ai_1 _272_ (
    .A1(_137_),
    .A2(_150_),
    .B1(_177_),
    .B2(_191_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__a31oi_1 _273_ (
    .A1(_134_),
    .A2(_137_),
    .A3(_158_),
    .B1(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nand4_1 _274_ (
    .A(_189_),
    .B(_194_),
    .C(_197_),
    .D(_199_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o21bai_1 _275_ (
    .A1(_182_),
    .A2(_186_),
    .B1_N(_185_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__xor2_1 _276_ (
    .A(_142_),
    .B(_183_),
    .X(_201_)
  );
  sky130_fd_sc_hd__xor2_1 _277_ (
    .A(_138_),
    .B(_201_),
    .X(_202_)
  );
  sky130_fd_sc_hd__xnor2_1 _278_ (
    .A(_200_),
    .B(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nor2_1 _279_ (
    .A(_142_),
    .B(_138_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__and2_0 _280_ (
    .A(_142_),
    .B(_138_),
    .X(_205_)
  );
  sky130_fd_sc_hd__nor2_1 _281_ (
    .A(_204_),
    .B(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o31ai_1 _282_ (
    .A1(_168_),
    .A2(_191_),
    .A3(_192_),
    .B1(_190_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__xor2_1 _283_ (
    .A(_206_),
    .B(_207_),
    .X(_208_)
  );
  sky130_fd_sc_hd__nand2_1 _284_ (
    .A(_173_),
    .B(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_177_),
    .B(_205_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o22ai_1 _286_ (
    .A1(_142_),
    .A2(_138_),
    .B1(_153_),
    .B2(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nor2_1 _287_ (
    .A(_138_),
    .B(_150_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__o211ai_1 _288_ (
    .A1(_134_),
    .A2(_142_),
    .B1(_138_),
    .C1(_158_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__a21oi_1 _289_ (
    .A1(_142_),
    .A2(_159_),
    .B1(_212_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__and3_1 _290_ (
    .A(_211_),
    .B(_213_),
    .C(_214_),
    .X(_215_)
  );
  sky130_fd_sc_hd__o211ai_1 _291_ (
    .A1(_156_),
    .A2(_203_),
    .B1(_209_),
    .C1(_215_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor4_1 _292_ (
    .A(_145_),
    .B(_146_),
    .C(_147_),
    .D(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor2b_1 _293_ (
    .A(_204_),
    .B_N(_207_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__o21ai_0 _294_ (
    .A1(_205_),
    .A2(_207_),
    .B1(_173_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(_155_),
    .B(_206_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__mux2i_1 _296_ (
    .A0(_142_),
    .A1(_138_),
    .S(_203_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o22ai_1 _297_ (
    .A1(_216_),
    .A2(_217_),
    .B1(_218_),
    .B2(_219_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a21oi_1 _298_ (
    .A1(_138_),
    .A2(_201_),
    .B1(_200_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__o21ai_0 _299_ (
    .A1(_138_),
    .A2(_201_),
    .B1(_155_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__o22ai_1 _300_ (
    .A1(_204_),
    .A2(_217_),
    .B1(_220_),
    .B2(_221_),
    .Y(_143_)
  );
  assign scan_out = scan_in;
  assign _139_ = B[0];
  assign _135_ = A[0];
  assign _134_ = ALU_CTRL[2];
  assign _132_ = ALU_CTRL[0];
  assign _133_ = ALU_CTRL[1];
  assign RESULT[0] = _145_;
  assign _140_ = B[1];
  assign _136_ = A[1];
  assign RESULT[1] = _146_;
  assign _141_ = B[2];
  assign _137_ = A[2];
  assign RESULT[2] = _147_;
  assign _142_ = B[3];
  assign _138_ = A[3];
  assign RESULT[3] = _148_;
  assign ZERO = _149_;
  assign OVERFLOW = _144_;
  assign CARRY_OUT = _143_;
endmodule
