/* Generated by Yosys 0.60+8 (git sha1 0e31e389f, g++ 13.1.0-8ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../rtl/4bitalu.v:1.1-81.10" *)
module alu_4bit(clk, rst_n, A, B, ALU_CTRL, RESULT, CARRY_OUT, ZERO, OVERFLOW);
  (* src = "../rtl/4bitalu.v:2.24-2.27" *)
  input clk;
  wire clk;
  (* src = "../rtl/4bitalu.v:3.24-3.29" *)
  input rst_n;
  wire rst_n;
  (* src = "../rtl/4bitalu.v:4.24-4.25" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "../rtl/4bitalu.v:5.24-5.25" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "../rtl/4bitalu.v:6.24-6.32" *)
  input [2:0] ALU_CTRL;
  wire [2:0] ALU_CTRL;
  (* src = "../rtl/4bitalu.v:8.24-8.30" *)
  output [3:0] RESULT;
  wire [3:0] RESULT;
  (* src = "../rtl/4bitalu.v:9.24-9.33" *)
  output CARRY_OUT;
  wire CARRY_OUT;
  (* src = "../rtl/4bitalu.v:10.24-10.28" *)
  output ZERO;
  wire ZERO;
  (* src = "../rtl/4bitalu.v:11.24-11.32" *)
  output OVERFLOW;
  wire OVERFLOW;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  (* src = "../rtl/4bitalu.v:6.24-6.32" *)
  wire _139_;
  (* src = "../rtl/4bitalu.v:6.24-6.32" *)
  wire _140_;
  (* src = "../rtl/4bitalu.v:6.24-6.32" *)
  wire _141_;
  (* src = "../rtl/4bitalu.v:4.24-4.25" *)
  wire _142_;
  (* src = "../rtl/4bitalu.v:4.24-4.25" *)
  wire _143_;
  (* src = "../rtl/4bitalu.v:4.24-4.25" *)
  wire _144_;
  (* src = "../rtl/4bitalu.v:4.24-4.25" *)
  wire _145_;
  (* src = "../rtl/4bitalu.v:5.24-5.25" *)
  wire _146_;
  (* src = "../rtl/4bitalu.v:5.24-5.25" *)
  wire _147_;
  (* src = "../rtl/4bitalu.v:5.24-5.25" *)
  wire _148_;
  (* src = "../rtl/4bitalu.v:5.24-5.25" *)
  wire _149_;
  (* src = "../rtl/4bitalu.v:9.24-9.33" *)
  wire _150_;
  (* src = "../rtl/4bitalu.v:11.24-11.32" *)
  wire _151_;
  (* src = "../rtl/4bitalu.v:8.24-8.30" *)
  wire _152_;
  (* src = "../rtl/4bitalu.v:8.24-8.30" *)
  wire _153_;
  (* src = "../rtl/4bitalu.v:8.24-8.30" *)
  wire _154_;
  (* src = "../rtl/4bitalu.v:8.24-8.30" *)
  wire _155_;
  (* src = "../rtl/4bitalu.v:10.24-10.28" *)
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  sky130_fd_sc_hd__clkinv_1 _231_ (
    .A(_144_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__clkinv_1 _232_ (
    .A(_143_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__and2_0 _233_ (
    .A(_149_),
    .B(_145_),
    .X(_159_)
  );
  sky130_fd_sc_hd__nor2_1 _234_ (
    .A(_149_),
    .B(_145_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nor2_1 _235_ (
    .A(_159_),
    .B(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(_148_),
    .B(_144_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2_1 _237_ (
    .A(_148_),
    .B(_144_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__xor2_1 _238_ (
    .A(_148_),
    .B(_144_),
    .X(_164_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _239_ (
    .A(_146_),
    .SLEEP(_142_),
    .X(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _240_ (
    .A(_147_),
    .B(_143_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__xor2_1 _241_ (
    .A(_147_),
    .B(_143_),
    .X(_167_)
  );
  sky130_fd_sc_hd__maj3_1 _242_ (
    .A(_147_),
    .B(_158_),
    .C(_165_),
    .X(_168_)
  );
  sky130_fd_sc_hd__maj3_1 _243_ (
    .A(_148_),
    .B(_157_),
    .C(_168_),
    .X(_169_)
  );
  sky130_fd_sc_hd__nand2b_1 _244_ (
    .A_N(_145_),
    .B(_149_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _245_ (
    .A(_139_),
    .SLEEP(_140_),
    .X(_171_)
  );
  sky130_fd_sc_hd__o2111ai_1 _246_ (
    .A1(_161_),
    .A2(_169_),
    .B1(_170_),
    .C1(_171_),
    .D1(_141_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nand2_1 _247_ (
    .A(_146_),
    .B(_142_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nor2_1 _248_ (
    .A(_146_),
    .B(_142_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _249_ (
    .A(_140_),
    .SLEEP(_139_),
    .X(_175_)
  );
  sky130_fd_sc_hd__a211oi_1 _250_ (
    .A1(_141_),
    .A2(_139_),
    .B1(_174_),
    .C1(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__o21ai_0 _251_ (
    .A1(_140_),
    .A2(_173_),
    .B1(_176_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__and3_1 _252_ (
    .A(_141_),
    .B(_139_),
    .C(_140_),
    .X(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(_146_),
    .B(_178_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__o211ai_1 _254_ (
    .A1(_146_),
    .A2(_141_),
    .B1(_175_),
    .C1(_142_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand3b_1 _255_ (
    .A_N(_141_),
    .B(_139_),
    .C(_140_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nor3b_1 _256_ (
    .A(_139_),
    .B(_140_),
    .C_N(_141_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nand4_1 _257_ (
    .A(_172_),
    .B(_177_),
    .C(_179_),
    .D(_180_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor3_1 _258_ (
    .A(_141_),
    .B(_139_),
    .C(_140_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__xnor2_1 _259_ (
    .A(_167_),
    .B(_173_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nand2_1 _260_ (
    .A(_183_),
    .B(_184_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(_167_),
    .B(_182_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__o211ai_1 _262_ (
    .A1(_141_),
    .A2(_147_),
    .B1(_143_),
    .C1(_175_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nand3_1 _263_ (
    .A(_185_),
    .B(_186_),
    .C(_187_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _264_ (
    .A(_171_),
    .SLEEP(_141_),
    .X(_189_)
  );
  sky130_fd_sc_hd__nand2b_1 _265_ (
    .A_N(_141_),
    .B(_171_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__o21ai_0 _266_ (
    .A1(_165_),
    .A2(_167_),
    .B1(_189_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a21oi_1 _267_ (
    .A1(_165_),
    .A2(_167_),
    .B1(_191_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _268_ (
    .A(_147_),
    .B(_178_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a21oi_1 _269_ (
    .A1(_181_),
    .A2(_193_),
    .B1(_166_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__or3_1 _270_ (
    .A(_188_),
    .B(_192_),
    .C(_194_),
    .X(_153_)
  );
  sky130_fd_sc_hd__or3_1 _271_ (
    .A(_146_),
    .B(_148_),
    .C(_147_),
    .X(_195_)
  );
  sky130_fd_sc_hd__o21ai_0 _272_ (
    .A1(_146_),
    .A2(_147_),
    .B1(_148_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__and3_1 _273_ (
    .A(_144_),
    .B(_195_),
    .C(_196_),
    .X(_197_)
  );
  sky130_fd_sc_hd__nand3_1 _274_ (
    .A(_144_),
    .B(_195_),
    .C(_196_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__a21oi_1 _275_ (
    .A1(_195_),
    .A2(_196_),
    .B1(_144_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__o21a_1 _276_ (
    .A1(_147_),
    .A2(_158_),
    .B1(_165_),
    .X(_200_)
  );
  sky130_fd_sc_hd__mux2i_1 _277_ (
    .A0(_146_),
    .A1(_143_),
    .S(_147_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__or4_1 _278_ (
    .A(_197_),
    .B(_199_),
    .C(_200_),
    .D(_201_),
    .X(_202_)
  );
  sky130_fd_sc_hd__o22ai_1 _279_ (
    .A1(_197_),
    .A2(_199_),
    .B1(_200_),
    .B2(_201_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _280_ (
    .A(_202_),
    .B(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__a22oi_1 _281_ (
    .A1(_146_),
    .A2(_142_),
    .B1(_147_),
    .B2(_143_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nor2_1 _282_ (
    .A(_166_),
    .B(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o21ai_0 _283_ (
    .A1(_164_),
    .A2(_206_),
    .B1(_183_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__a21o_1 _284_ (
    .A1(_164_),
    .A2(_206_),
    .B1(_207_),
    .X(_208_)
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(_164_),
    .B(_182_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__o211ai_1 _286_ (
    .A1(_141_),
    .A2(_148_),
    .B1(_144_),
    .C1(_175_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o211ai_1 _287_ (
    .A1(_163_),
    .A2(_181_),
    .B1(_209_),
    .C1(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__a21oi_1 _288_ (
    .A1(_148_),
    .A2(_178_),
    .B1(_211_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__o211ai_1 _289_ (
    .A1(_190_),
    .A2(_204_),
    .B1(_208_),
    .C1(_212_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__o31ai_1 _290_ (
    .A1(_199_),
    .A2(_200_),
    .A3(_201_),
    .B1(_198_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__xor2_1 _291_ (
    .A(_149_),
    .B(_195_),
    .X(_214_)
  );
  sky130_fd_sc_hd__xor2_1 _292_ (
    .A(_145_),
    .B(_214_),
    .X(_215_)
  );
  sky130_fd_sc_hd__xnor2_1 _293_ (
    .A(_213_),
    .B(_215_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__o31ai_1 _294_ (
    .A1(_163_),
    .A2(_166_),
    .A3(_205_),
    .B1(_162_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__xor2_1 _295_ (
    .A(_161_),
    .B(_217_),
    .X(_218_)
  );
  sky130_fd_sc_hd__nand2_1 _296_ (
    .A(_183_),
    .B(_218_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nor2_1 _297_ (
    .A(_160_),
    .B(_181_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__a21oi_1 _298_ (
    .A1(_149_),
    .A2(_178_),
    .B1(_220_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _299_ (
    .A(_161_),
    .B(_182_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__o211ai_1 _300_ (
    .A1(_141_),
    .A2(_149_),
    .B1(_145_),
    .C1(_175_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__and3_1 _301_ (
    .A(_221_),
    .B(_222_),
    .C(_223_),
    .X(_224_)
  );
  sky130_fd_sc_hd__o211ai_1 _302_ (
    .A1(_190_),
    .A2(_216_),
    .B1(_219_),
    .C1(_224_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor4_1 _303_ (
    .A(_152_),
    .B(_153_),
    .C(_154_),
    .D(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2b_1 _304_ (
    .A(_160_),
    .B_N(_217_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__o21ai_0 _305_ (
    .A1(_159_),
    .A2(_217_),
    .B1(_183_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _306_ (
    .A(_216_),
    .SLEEP(_145_),
    .X(_227_)
  );
  sky130_fd_sc_hd__o211ai_1 _307_ (
    .A1(_149_),
    .A2(_216_),
    .B1(_189_),
    .C1(_161_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__o22ai_1 _308_ (
    .A1(_225_),
    .A2(_226_),
    .B1(_227_),
    .B2(_228_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a21oi_1 _309_ (
    .A1(_145_),
    .A2(_214_),
    .B1(_213_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__o21ai_0 _310_ (
    .A1(_145_),
    .A2(_214_),
    .B1(_189_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__o22ai_1 _311_ (
    .A1(_160_),
    .A2(_226_),
    .B1(_229_),
    .B2(_230_),
    .Y(_150_)
  );
  assign _146_ = B[0];
  assign _142_ = A[0];
  assign _141_ = ALU_CTRL[2];
  assign _139_ = ALU_CTRL[0];
  assign _140_ = ALU_CTRL[1];
  assign _149_ = B[3];
  assign _145_ = A[3];
  assign _148_ = B[2];
  assign _144_ = A[2];
  assign _147_ = B[1];
  assign _143_ = A[1];
  assign RESULT[0] = _152_;
  assign RESULT[1] = _153_;
  assign RESULT[2] = _154_;
  assign RESULT[3] = _155_;
  assign ZERO = _156_;
  assign OVERFLOW = _151_;
  assign CARRY_OUT = _150_;
endmodule
